# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-30 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password1', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password1', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('bday', models.DateField()),
                ('number', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=40)),
                ('pin_code', models.IntegerField()),
            ],
        ),
    ]
